name: 'Setup nodejs'
description: 'Setup nodejs'
author: 'Jean-Michel FRANCOIS'
secrets:
  NPM_TOKEN:
    description: 'The NPM token to use'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@9582c75426f692964c57b8c0143841239566449 # v4.0.0
      with:
        version: 10

    - name: Set up Node.js
      uses: actions/setup-node@1e60f620b954291f3b8c1942277c969252b4368e #v4.1.0
      with:
        node-version-file: '.tool-versions'
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'